# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85f3af9cdae64dd8ab5be3c4f8d78035c8f0a9dbbc2f3ec05c7506a53ef4386c6dbacbecdc8d86d5377ee605bfaab884a08b1c5fd92e17a66645045c3d3db529

test:
  secret_key_base: cac94129b8a49a56ce6a1010dcfa00f423b27d5e884a940a77bf79b64587461b9b5c92a915af6f9c54729f3a931c42dd280bc1987dbdb2acaee15f4dee0fb3e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
